# Generated by Django 5.2.6 on 2026-02-08 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_student_table_status_links'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study_materials_table',
            name='study_material',
            field=models.FileField(upload_to=''),
        ),
    ]
