# Generated by Django 5.2.6 on 2026-03-14 04:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_study_materials_table_study_material'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review_table',
            name='STUDY_MATERIALS',
        ),
        migrations.AddField(
            model_name='review_table',
            name='LINK',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.links'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='links',
            name='status',
            field=models.CharField(default='Active', max_length=100),
        ),
        migrations.CreateModel(
            name='ChatHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=10)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('STUDENT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.student_table')),
            ],
        ),
    ]
